name: Build TFT Meta Snapshot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours

permissions:
  contents: write  # allow the workflow to push commits

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --no-audit --no-fund

      - name: Make .env
        run: |
          cp .env.example .env
          sed -i "s|replace_me|${{ secrets.RIOT_API_KEY }}|g" .env
          echo "PLATFORMS=NA1,EUW1,KR" >> .env
          echo "PATCH=15.4" >> .env
          echo "SEED_SUMMONERS=1500" >> .env
          echo "MATCHES_PER=20" >> .env
          echo "MIN_PICKS=200" >> .env
          echo "MIN_PICKS_ITEM_COMBO=50" >> .env

      - name: Run pipeline
        run: npm start

      - name: Commit updated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # Force add because data/*.json is ignored by .gitignore
          git add -f data/meta_15.4.json data/meta_current.json || true
          git commit -m "Update meta (15.4 NA1/EUW1/KR, Dia+Masters+)" || true
          git push || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: meta-15.4
          path: |
            data/meta_15.4.json
            data/meta_current.json
