name: Collect TFT Slices

on:
  workflow_dispatch:        # <-- this makes the "Run workflow" button appear
  schedule:
    - cron: "0 */6 * * *"   # optional: every 6 hours

permissions:
  contents: write

jobs:
  collect:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci || npm i --no-audit --no-fund

      - name: Make .env
        shell: bash
        run: |
          set -euo pipefail
          cp .env.example .env
          sed -i "s|replace_me|${{ secrets.RIOT_API_KEY }}|g" .env
          {
            echo "PLATFORMS=NA1,EUW1,KR"
            echo "SEED_SUMMONERS=500"     # smaller for quick debug pass
            echo "MATCHES_PER=10"
            echo "PATCH="                 # collect ALL patches (blank)
            echo "QUEUE_FILTER="          # allow any queue for this debug run
            echo "MAX_AGE_DAYS=0"         # no age filter for this debug run
          } >> .env

      - name: Collect slices
        run: npm run collect

      - name: Verify slices & list files
        shell: bash
        run: |
          set -e
          echo "== tree data =="
          ls -R data || true
          echo "== check for NDJSON =="
          f=$(ls -1 data/staging/*/*.ndjson 2>/dev/null | head -n1 || true)
          if [[ -z "$f" ]]; then
            echo "❌ No NDJSON files were written"; exit 1
          fi
          wc -l "$f" | awk '{print "✅ Lines in", $2, "=", $1}'
          head -n 5 "$f" || true

      - name: Commit slices & state
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f data/staging/** data/state/** || true
          git commit -m "Collect slices" || true
          git push || true
