name: Collect TFT Slices

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Build the .env used by the collector (ranked + recent only)
      - name: Make .env (Diamond+ ranked, most current)
        run: |
          KEY="${{ secrets.RIOT_API_KEY }}"
          KEY="$(printf %s "$KEY" | tr -d '\r\n\t ')"   # trim hidden whitespace
          {
            echo "RIOT_API_KEY=$KEY"
            echo "PLATFORMS=NA1,EUW1,KR"
            echo "SEED_SUMMONERS=1500"   # width; not a filter
            echo "MATCHES_PER=10"        # depth; not a filter
            echo "PATCH="                # keep BLANK in collector
            echo "QUEUE_FILTER=1100"     # ranked only
            echo "MAX_AGE_DAYS=7"        # “most current” (change to 3/14 as you like)
          } > .env

      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Collect slices
        run: npm run collect

      - name: Verify slices & list files
        run: |
          echo "== tree data =="; ls -R data || true
          F=$(ls -1 data/staging/*/*.ndjson 2>/dev/null | head -n1 || true)
          if [ -z "$F" ]; then
            echo "❌ No NDJSON files were written"; exit 1
          fi
          wc -l "$F" | awk '{print "✅ Lines in", $2, "=", $1}'
          head -n 5 "$F" || true

      - name: Commit slices & state
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f data/staging/** data/state/** || true
          git commit -m "Collect slices" || true
          git push || true
